### ISSUE TITLE
ssl-cert group not existing

### ISSUE THREAD

**Issue by mtancoigne** [innophi/ansible-letsencrypt#1]
Hi !

Provisionning fails with this error, on an Ubuntu 16.04 server:
```text
TASK [letsencrypt : create private directory] **********************************
task path: /home/kure/Dev/ExperimentsLabs/TheGame/vm/provisioning/roles/letsencrypt/tasks/letsencrypt.yml:13
fatal: [theproj]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chgrp failed: failed to look up group ssl-cert", "owner": "letsencrypt", "path": "/var/lib/letsencrypt/private/", "size": 4096, "state": "directory", "uid": 1001}          
```

The `ssl-cert` group doesn't exist. 

I have been able to resolve it adding a task that creates the group. Do you want me to make a PR for this, or is there a better alternative to create the group ?

**Comment by laurentj** [comment]
Hi,

I think that on debian, ssl-cert group is already created when installing the ssl-cert package

**Comment by mtancoigne** [comment]
Yes, that package was missing on my system :)
